node{
	def mvnHome
	def dockerHome
	stage('Checkout'){
		git url: 'file://C:/Users/Public/Automation/Dev New Learning/bootapp-restful-crud-SBA3', branch: 'master'
		mvnHome = tool 'Local Maven'
		dockerHome = tool 'MyDocker'
	}
	
	stage('Build'){
		bat(/"${mvnHome}\bin\mvn" clean package/)
	}
	
	stage('Containerize"){
		bat(/"${dockerHome}\Docker\resources\bin\docker" build -t bootapp-restful-crud-SBA3:latest ./)
	}
}